apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oma-k8s-bridge.fullname" . }}
  labels:
    {{- include "oma-k8s-bridge.labels" . | nindent 4 }}
data:
  K8S_NAMESPACE: {{ .Values.config.namespace | quote }}
  SANDBOX_IMAGE: {{ .Values.config.sandboxImage | quote }}
  RUNTIME_CLASS: {{ .Values.config.runtimeClass | quote }}
  SANDBOX_SERVICE_ACCOUNT: {{ .Values.config.serviceAccount | quote }}
