apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-bridge.fullname" . }}
  labels:
    {{- include "k8s-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  K8S_BRIDGE_TOKEN: {{ .Values.secret.token | b64enc | quote }}
