{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-bridge.serviceAccountName" . }}
  labels:
    {{- include "k8s-bridge.labels" . | nindent 4 }}
{{- end }}
